- name: Docker build and push playbook
  hosts: 43.204.38.39   # Use 'localhost' if running on the same machine
  become: yes  # Run tasks with sudo privileges

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes   

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Build Docker Image
      community.docker.docker_image:
        name: petstore
        build:
          path: /home/ubuntu/jpetstore-6  # Updated path
          tag: latest
        state: present

    - name: Tag Docker Image
      community.docker.docker_image:
        name: foxe03/petstore
        tag: latest
        source: petstore:latest
        state: present

    - name: Log in to Docker Hub
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Push Docker Image
      community.docker.docker_image:
        name: foxe03/petstore
        tag: latest
        push: yes

    - name: Run Docker Container
      community.docker.docker_container:
        name: pet1
        image: foxe03/petstore:latest
        state: started
        ports:
          - "8085:8080"
